### ISSUE TITLE
SearchResults returning url with /index on the end

### ISSUE THREAD

**Issue by NorseGaud** [gburgett/hugo-search-index#1]
Search results are working, but the urls all have /index on the end: `http://localhost:1313/documentation/CI-CD/anka/index`

Do you know what could cause this?

**Comment by NorseGaud** [comment]
Oddly enough, the tests pass. Could this be a problem with the versions I'm using of hugo?

**Comment by NorseGaud** [comment]
@gburgett, this repo maintained anymore?

**Comment by gburgett** [comment]
Hey, sorry no it's not!  I haven't been using it personally since I switched over to Algolia on my personal site. If I had to guess then the issue would be inside the gulp task that populates the search index, it's probably incorrectly joining URLs together.  Feel free to fork!
